version: '3.10'

services:
  backend:
    build:
      context: ./backend
    container_name: django_app
    volumes:
      - ./backend/media:/app/media
      - ./backend/db.sqlite3:/app/db.sqlite3

    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=127.0.0.1,localhost

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    ports:
      - "8080:8080"